/**
 * Writes _redirects, sitemap.xml and robots.txt into dist/ from src/routes.ts.
 *
 * Runs after the build (npm postbuild) because all three land in dist/ root.
 *
 * _redirects is what makes a direct visit to /about work. Cloudflare serves
 * index.html for those paths and React takes over from there. Note what is
 * NOT here: a catch-all. A blanket /* rule would answer 200 for every URL that
 * has ever existed, which would keep the old Squarespace /events-library and
 * /courses-library pages alive forever as blank 200s. Listing the real routes
 * instead means anything else falls through to a genuine 404, which is what
 * tells Google those pages are gone.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ROUTES, SITE_ORIGIN } from '../src/routes.ts';

const DIST = join(dirname(fileURLToPath(import.meta.url)), '..', 'dist');
const today = new Date().toISOString().slice(0, 10);

// '/' is dist/index.html already; the rest need telling.
const redirects = ROUTES.filter((r) => r.path !== '/')
  .map((r) => `${r.path.padEnd(14)}/index.html  200`)
  .join('\n');
writeFileSync(
  join(DIST, '_redirects'),
  `# Generated by scripts/gen-static.ts from src/routes.ts — do not edit.\n` +
    `# Real routes only. Everything else 404s on purpose.\n${redirects}\n`,
);

const urls = ROUTES.map(
  (r) =>
    `  <url>\n    <loc>${SITE_ORIGIN}${r.path}</loc>\n` +
    `    <lastmod>${today}</lastmod>\n    <priority>${r.priority.toFixed(1)}</priority>\n  </url>`,
).join('\n');
writeFileSync(
  join(DIST, 'sitemap.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`,
);

writeFileSync(
  join(DIST, 'robots.txt'),
  `User-agent: *\nAllow: /\n\nSitemap: ${SITE_ORIGIN}/sitemap.xml\n`,
);

console.log(`[static] ${ROUTES.length} routes -> _redirects, sitemap.xml, robots.txt`);
